/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF, useAnimations, useVideoTexture, useHelper, SpotLight, PivotControls } from '@react-three/drei'
import RoomFile from '../../assets/models/portfolio-room-arcade.glb'
import { useTheme } from '../../Context/ContextZustand'
import { useEffect } from 'react'
import gsap, { interpolate } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { useFrame,  } from '@react-three/fiber'
import * as THREE from 'three'

// TEXTURES
import ScreenTexture from "../../assets/textures/screen_video.mp4"
import ArcadeScreenTexture from "../../assets/textures/arcade_video.mp4"
import TextureNoise1 from "../../assets/textures/screen_noise1.mp4"
import TextureNoise2 from "../../assets/textures/screen_noise2.mp4"
import { ArrowHelper, AxesHelper, Box3Helper, BoxGeometry, BoxHelper, GridHelper, PlaneHelper, PointLightHelper, SpotLightHelper } from 'three'

function floatAnim(item, t) {
  item.current.rotation.x = 1 - (1+Math.sin(t/1.5)/20)
  item.current.rotation.y =Math.cos(t/4) / 8
  item.current.rotation.z = Math.sin(t/4) /8
  item.current.position.y =  0.5-(1+ Math.sin(t/1.5) /10)
}

export function RoomModel(props) {
  gsap.registerPlugin(ScrollTrigger)
  const group = useRef()
  const scene = useRef()
  const miniLamp = useRef()

  const { nodes, materials, animations } = useGLTF(RoomFile)
  const { actions } = useAnimations(animations, group)

  const PCvideo = useVideoTexture(ScreenTexture)
  const Arcadevideo = useVideoTexture(ArcadeScreenTexture)
  const PCNoise = useVideoTexture(TextureNoise1)
  const ArcadeNoise = useVideoTexture(TextureNoise2)
  const PCScreen = useRef()
  const ArcadeScreen = useRef()
  const Tesseract = useRef()
  const bigGear = useRef()

  let Theme = useTheme()
  var Rotlerp = {
    current : 0,
    target: 0,
    ease: 0.01,
    status: true
}
const [GearsRotation, setGearsRotation] = useState({status: false, direction: false})

  // useSetRoom(nodes.Scene)
  useEffect(() => {
    if(Theme.mode === 'light'){
      gsap.to(miniLamp.current.color, {r: 0, g:0, b:0})
      gsap.to(lamp.current.material.emissive, {r: 0, g:0, b:0})
      gsap.to(Tesseract.current.material.emissive, {r: 0, g:0, b:0})
      
      
      
    }
    else
    {
      
      gsap.to(Tesseract.current.material.emissive, {r: 1, g:0, b:0, duration: 10})
      gsap.to(lamp.current.material.emissive, {r: 1, g:0.5, b:0, delay: 2})
      gsap.to(miniLamp.current.color, {r: 1, g:1, b:1, delay: 2}) 
      
      
      
    }
    
  }, [Theme])

  
  useEffect(() => {
    const tl = gsap.timeline()
    const el = props.containerRef.current
    console.log(bigGear);
    // tl.to(scene.current.position, {x: 5, duration:10})
    tl.to(scene.current.position, {x: () =>{ return window.innerWidth * 0.0055}, ease: 1,
        scrollTrigger: {
            trigger: el.querySelector('.separator'),
            scrub: 0.5,
            start: "top top",
            end: "bottom bottom",
            scroller: el.querySelector('.page'),
            invalidateOnRefresh: true,
        }
    })
    // tl.to(bigGear.current, {rotateY: 0.01, repeat: -1})
    ScrollTrigger.create( {
      trigger: el.querySelector('.separator'),
      start: "top top",
      scrub: 0.5,
      end: "bottom bottom",
      scroller: el.querySelector('.page'),
      markers: true,
      onEnter: () => setGearsRotation({status: true, direction: false}),
      onLeave:() => setGearsRotation({status: false, direction: false}),
      onEnterBack: () => setGearsRotation({status: true, direction: true}),
      onLeaveBack: () => setGearsRotation({status: false, direction: true}),
      onUpdate: (self) => {
          Rotlerp.status =true
          Rotlerp.target = self.progress
          console.log(self.progress);
      }
    })
    console.log(bigGear.current);
    
  
 

  }, [])

  useEffect(() => {
    PCScreen.current.material = new THREE.MeshBasicMaterial({map: PCvideo})
    ArcadeScreen.current.material = new THREE.MeshBasicMaterial({map: Arcadevideo})
    actions['Cube.099Action.001']?.play()
  
  }, [PCvideo, Arcadevideo, actions])
  

  var  lerp = {
    currentX : 0,
    targetX: 0,
    currentY : 0,
    targetY: 0,
    ease: 0.1 
  }
  
  window.addEventListener('mousemove', (e) => {
    var rotationX = ((e.clientX - window.innerWidth / 2) * 2) / window.innerWidth
    var rotationY = ((e.clientY - window.innerHeight / 2) * 2) / window.innerHeight
    lerp.targetX = rotationX * 0.05
    lerp.targetY = rotationY * 0.05
    
})
const lamp = useRef()

useFrame((state) => {
  scene.current.rotation.y = lerp.currentX
  lerp.currentX = gsap.utils.interpolate(lerp.currentX, lerp.targetX, lerp.ease)
  scene.current.rotation.x = lerp.currentY
  lerp.currentY = gsap.utils.interpolate(lerp.currentY, lerp.targetY, lerp.ease)

  if(GearsRotation.status){
    bigGear.current.rotateY(GearsRotation.direction ? -0.01 : 0.01)
  }
  



  const t = state.clock.getElapsedTime() 

  // RotationProgress = gsap.utils.interpolate(Rotlerp.current, Rotlerp.target, Rotlerp.ease) % 1
  // bigGear.current.rotateY(gsap.interpolate())
  // floatAnim(rocket, t)
  
})

  return (
    <group ref={group} {...props} dispose={null} scale={0.21} position={[0,-1,0]} >
      <group ref={scene} name="Scene"  >
        <group name="RoomWalls" position={[0.57, 5, 1.98]} rotation={[0, Math.PI / 4, 0]}>
          <mesh name="Cube008_1" castShadow receiveShadow geometry={nodes.Cube008_1.geometry} material={materials.Base} />
          <mesh name="Cube008_2" castShadow receiveShadow geometry={nodes.Cube008_2.geometry} material={materials.Wall} />
          <mesh name="Cube008_3" castShadow receiveShadow geometry={nodes.Cube008_3.geometry} material={materials.floor2} />
        </group>
        <group name="MiniLampe"  position={[-2.44, 5.3, -1.13]} rotation={[0, Math.PI / 4, 0]} >
          <mesh name="Cylinder002_1" ref={lamp} material-color="blue" castShadow receiveShadow geometry={nodes.Cylinder002_1.geometry} material={materials.Material}/>
          <pointLight ref={miniLamp} scale={0.21} position={[0,0.4,0]} intensity={1} distance={200} color={"#000"} />
          <mesh name="Cylinder002_2" castShadow receiveShadow geometry={nodes.Cylinder002_2.geometry} material={materials.lampBase} />
        </group>
        <mesh name="Plane" castShadow receiveShadow geometry={nodes.Plane.geometry} material={materials.WindowFrame} position={[-0.73, 5.56, -3.31]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} />
        <group name="Rocket"  position={[-4.26, 4.86, 0.63]} rotation={[0, 1.2, 0]}>
          <mesh name="Cone" castShadow receiveShadow geometry={nodes.Cone.geometry} material={materials['Rocket.001']} />
          <mesh name="Cone_1" castShadow receiveShadow geometry={nodes.Cone_1.geometry} material={materials.RocketTop} />
        </group>
        <mesh name="Cube" castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials['tableTop.001']} position={[-2.73, 1.52, 0.3]} rotation={[0, Math.PI / 4, 0]} />
        <mesh name="Cube001" castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials['TableLeg.001']} position={[-3.91, 0.29, 1.48]} rotation={[0, Math.PI / 4, 0]} />
        <group name="Cube002" position={[-3.91, 0.41, 1.48]} rotation={[0, Math.PI / 4, 0]}>
          <mesh name="Cube007_1" castShadow receiveShadow geometry={nodes.Cube007_1.geometry} material={materials['TableLeg.001']} />
          <mesh name="Cube007_2" castShadow receiveShadow geometry={nodes.Cube007_2.geometry} material={materials['TableLegBlack.001']} />
        </group>
        <mesh name="Cube004" castShadow receiveShadow geometry={nodes.Cube004.geometry} material={materials['tableTop.001']} position={[-3.18, 1.85, -0.19]} rotation={[0, Math.PI / 4, 0]} />
        <mesh name="Circle" castShadow receiveShadow geometry={nodes.Circle.geometry} material={materials['leaf.001']} position={[-1.64, 1.83, -1.25]} rotation={[Math.PI, -0.28, Math.PI]} />
        <mesh name="Circle001" castShadow receiveShadow geometry={nodes.Circle001.geometry} material={materials['leaf.001']} position={[-1.64, 1.83, -1.25]} rotation={[Math.PI, -1.2, Math.PI]} />
        <mesh name="Circle002" castShadow receiveShadow geometry={nodes.Circle002.geometry} material={materials['leaf.001']} position={[-1.64, 1.83, -1.25]} rotation={[0, -0.51, 0]} />
        <mesh name="Circle003" castShadow receiveShadow geometry={nodes.Circle003.geometry} material={materials['leaf.001']} position={[-1.64, 1.83, -1.25]} rotation={[-Math.PI, 0.89, -Math.PI]} />
        <mesh name="Circle004" castShadow receiveShadow geometry={nodes.Circle004.geometry} material={materials['leaf.001']} position={[-1.64, 1.83, -1.25]} rotation={[0, 1.17, 0]} />
        <mesh name="Circle005" castShadow receiveShadow geometry={nodes.Circle005.geometry} material={materials['leaf.001']} position={[-1.64, 1.83, -1.25]} rotation={[0, 0.46, 0]} />
        <mesh name="Circle006" castShadow receiveShadow geometry={nodes.Circle006.geometry} material={materials['leaf.001']} position={[-1.64, 1.83, -1.25]} rotation={[0, 0.45, 0]} />
        <mesh name="Circle007" castShadow receiveShadow geometry={nodes.Circle007.geometry} material={materials['leaf.001']} position={[-1.64, 1.83, -1.25]} rotation={[0, -0.13, 0]} />
        <mesh name="Circle008" castShadow receiveShadow geometry={nodes.Circle008.geometry} material={materials['leaf.001']} position={[-1.64, 1.83, -1.25]} rotation={[-Math.PI, 1.03, -Math.PI]} />
        <mesh name="Circle009" castShadow receiveShadow geometry={nodes.Circle009.geometry} material={materials['leaf.001']} position={[-1.64, 1.83, -1.25]} rotation={[0, -1.34, 0]} />
        <mesh name="Circle010" castShadow receiveShadow geometry={nodes.Circle010.geometry} material={materials['leaf.001']} position={[-1.64, 1.83, -1.25]} rotation={[-Math.PI, 0.16, -Math.PI]} />
        <group name="Cylinder" position={[-1.61, 1.74, -1.25]} rotation={[0, Math.PI / 4, 0]}>
          <mesh name="Cylinder_1" castShadow receiveShadow geometry={nodes.Cylinder_1.geometry} material={materials['pot.001']} />
          <mesh name="Cylinder_2" castShadow receiveShadow geometry={nodes.Cylinder_2.geometry} material={materials['soil.001']} />
        </group>
        <mesh name="screen" castShadow receiveShadow geometry={nodes.screen.geometry} material={materials['ScreenPC.001']} position={[-3.18, 2.53, -0.19]} rotation={[0, Math.PI / 4, 0]} />
        <mesh name="screen001" ref={PCScreen} castShadow receiveShadow geometry={nodes.screen001.geometry} material={materials['Screen.001']} position={[-3.18, 2.53, -0.19]} rotation={[0, Math.PI / 4, 0]} />
        <mesh name="Cube007" castShadow receiveShadow geometry={nodes.Cube007.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube008" castShadow receiveShadow geometry={nodes.Cube008.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube009" castShadow receiveShadow geometry={nodes.Cube009.geometry} material={materials.Key} position={[-3.16, 1.65, 0.7]} rotation={[0.1, 0.78, -0.05]} />
        <mesh name="Cube010" castShadow receiveShadow geometry={nodes.Cube010.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube011" castShadow receiveShadow geometry={nodes.Cube011.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube012" castShadow receiveShadow geometry={nodes.Cube012.geometry} material={materials.Key} position={[-3.33, 1.65, 0.66]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube013" castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube014" castShadow receiveShadow geometry={nodes.Cube014.geometry} material={materials.Key} position={[-3.23, 1.65, 0.59]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube015" castShadow receiveShadow geometry={nodes.Cube015.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube016" castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Key} position={[-2.54, 1.65, 0.25]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube017" castShadow receiveShadow geometry={nodes.Cube017.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube018" castShadow receiveShadow geometry={nodes.Cube018.geometry} material={materials.Key} position={[-2.81, 1.64, 0.62]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube019" castShadow receiveShadow geometry={nodes.Cube019.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube020" castShadow receiveShadow geometry={nodes.Cube020.geometry} material={materials.Key} position={[-3.23, 1.65, 0.59]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube021" castShadow receiveShadow geometry={nodes.Cube021.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube022" castShadow receiveShadow geometry={nodes.Cube022.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube023" castShadow receiveShadow geometry={nodes.Cube023.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube024" castShadow receiveShadow geometry={nodes.Cube024.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube025" castShadow receiveShadow geometry={nodes.Cube025.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube026" castShadow receiveShadow geometry={nodes.Cube026.geometry} material={materials.Key} position={[-3.23, 1.65, 0.6]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube027" castShadow receiveShadow geometry={nodes.Cube027.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube028" castShadow receiveShadow geometry={nodes.Cube028.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube029" castShadow receiveShadow geometry={nodes.Cube029.geometry} material={materials.Key} position={[-3.31, 1.65, 0.68]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube030" castShadow receiveShadow geometry={nodes.Cube030.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube031" castShadow receiveShadow geometry={nodes.Cube031.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube032" castShadow receiveShadow geometry={nodes.Cube032.geometry} material={materials.Key} position={[-3.23, 1.65, 0.6]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube033" castShadow receiveShadow geometry={nodes.Cube033.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube034" castShadow receiveShadow geometry={nodes.Cube034.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube035" castShadow receiveShadow geometry={nodes.Cube035.geometry} material={materials.Key} position={[-3.07, 1.64, 0.78]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube036" castShadow receiveShadow geometry={nodes.Cube036.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube037" castShadow receiveShadow geometry={nodes.Cube037.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube038" castShadow receiveShadow geometry={nodes.Cube038.geometry} material={materials.Key} position={[-3.23, 1.65, 0.6]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube039" castShadow receiveShadow geometry={nodes.Cube039.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube040" castShadow receiveShadow geometry={nodes.Cube040.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube041" castShadow receiveShadow geometry={nodes.Cube041.geometry} material={materials.Key} position={[-2.61, 1.66, 0.15]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube042" castShadow receiveShadow geometry={nodes.Cube042.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube043" castShadow receiveShadow geometry={nodes.Cube043.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube044" castShadow receiveShadow geometry={nodes.Cube044.geometry} material={materials.Key} position={[-3.23, 1.65, 0.6]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube045" castShadow receiveShadow geometry={nodes.Cube045.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube046" castShadow receiveShadow geometry={nodes.Cube046.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube047" castShadow receiveShadow geometry={nodes.Cube047.geometry} material={materials.Key} position={[-3.22, 1.65, 0.59]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube048" castShadow receiveShadow geometry={nodes.Cube048.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube049" castShadow receiveShadow geometry={nodes.Cube049.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube050" castShadow receiveShadow geometry={nodes.Cube050.geometry} material={materials.Key} position={[-3.23, 1.65, 0.6]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube051" castShadow receiveShadow geometry={nodes.Cube051.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube052" castShadow receiveShadow geometry={nodes.Cube052.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube054" castShadow receiveShadow geometry={nodes.Cube054.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube055" castShadow receiveShadow geometry={nodes.Cube055.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube056" castShadow receiveShadow geometry={nodes.Cube056.geometry} material={materials.Key} position={[-3.23, 1.65, 0.6]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube057" castShadow receiveShadow geometry={nodes.Cube057.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube058" castShadow receiveShadow geometry={nodes.Cube058.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube060" castShadow receiveShadow geometry={nodes.Cube060.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube061" castShadow receiveShadow geometry={nodes.Cube061.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube062" castShadow receiveShadow geometry={nodes.Cube062.geometry} material={materials.Key} position={[-3.24, 1.65, 0.6]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube063" castShadow receiveShadow geometry={nodes.Cube063.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube064" castShadow receiveShadow geometry={nodes.Cube064.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube066" castShadow receiveShadow geometry={nodes.Cube066.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube067" castShadow receiveShadow geometry={nodes.Cube067.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube068" castShadow receiveShadow geometry={nodes.Cube068.geometry} material={materials.Key} position={[-3.24, 1.65, 0.6]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube069" castShadow receiveShadow geometry={nodes.Cube069.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube070" castShadow receiveShadow geometry={nodes.Cube070.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube071" castShadow receiveShadow geometry={nodes.Cube071.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube072" castShadow receiveShadow geometry={nodes.Cube072.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube073" castShadow receiveShadow geometry={nodes.Cube073.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube074" castShadow receiveShadow geometry={nodes.Cube074.geometry} material={materials.Key} position={[-3.24, 1.65, 0.6]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube075" castShadow receiveShadow geometry={nodes.Cube075.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube077" castShadow receiveShadow geometry={nodes.Cube077.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube078" castShadow receiveShadow geometry={nodes.Cube078.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube079" castShadow receiveShadow geometry={nodes.Cube079.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube081" castShadow receiveShadow geometry={nodes.Cube081.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube083" castShadow receiveShadow geometry={nodes.Cube083.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube084" castShadow receiveShadow geometry={nodes.Cube084.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube085" castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube089" castShadow receiveShadow geometry={nodes.Cube089.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube090" castShadow receiveShadow geometry={nodes.Cube090.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube091" castShadow receiveShadow geometry={nodes.Cube091.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube092" castShadow receiveShadow geometry={nodes.Cube092.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube095" castShadow receiveShadow geometry={nodes.Cube095.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube096" castShadow receiveShadow geometry={nodes.Cube096.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube097" castShadow receiveShadow geometry={nodes.Cube097.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube098" castShadow receiveShadow geometry={nodes.Cube098.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube100" castShadow receiveShadow geometry={nodes.Cube100.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube101" castShadow receiveShadow geometry={nodes.Cube101.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube102" castShadow receiveShadow geometry={nodes.Cube102.geometry} material={materials.Key} position={[-3.29, 1.65, 0.61]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube103" castShadow receiveShadow geometry={nodes.Cube103.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube104" castShadow receiveShadow geometry={nodes.Cube104.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube107" castShadow receiveShadow geometry={nodes.Cube107.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube109" castShadow receiveShadow geometry={nodes.Cube109.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube110" castShadow receiveShadow geometry={nodes.Cube110.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube111" castShadow receiveShadow geometry={nodes.Cube111.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube112" castShadow receiveShadow geometry={nodes.Cube112.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube113" castShadow receiveShadow geometry={nodes.Cube113.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube115" castShadow receiveShadow geometry={nodes.Cube115.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube116" castShadow receiveShadow geometry={nodes.Cube116.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube117" castShadow receiveShadow geometry={nodes.Cube117.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube118" castShadow receiveShadow geometry={nodes.Cube118.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube119" castShadow receiveShadow geometry={nodes.Cube119.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube121" castShadow receiveShadow geometry={nodes.Cube121.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube122" castShadow receiveShadow geometry={nodes.Cube122.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube123" castShadow receiveShadow geometry={nodes.Cube123.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube124" castShadow receiveShadow geometry={nodes.Cube124.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube125" castShadow receiveShadow geometry={nodes.Cube125.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube127" castShadow receiveShadow geometry={nodes.Cube127.geometry} material={materials.Key} position={[-3.27, 1.65, 0.63]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube130" castShadow receiveShadow geometry={nodes.Cube130.geometry} material={materials.Key} position={[-3.24, 1.65, 0.66]} rotation={[0.1, 0.78, -0.06]} />
        <mesh name="Cube006" castShadow receiveShadow geometry={nodes.Cube006.geometry} material={materials['keyboard.001']} position={[-2.73, 1.63, 0.29]} rotation={[0, Math.PI / 4, 0.01]} />
        <mesh name="Cube005" castShadow receiveShadow geometry={nodes.Cube005.geometry} material={materials['keyboard.001']} position={[-2.73, 1.63, 0.29]} rotation={[0, Math.PI / 4, 0.01]} />
        <mesh name="Cube053" castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials['tableTop.001']} position={[-3.21, 3.69, -0.38]} rotation={[0, Math.PI / 4, 0]} />
        <mesh name="Cube059" castShadow receiveShadow geometry={nodes.Cube059.geometry} material={materials['tableTop.001']} position={[-2.76, 5.24, -0.83]} rotation={[0, Math.PI / 4, 0]} />
        <mesh name="Cylinder001" castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={materials['TableLeg.001']} position={[-3.36, 1.72, 1.38]} rotation={[-Math.PI, 1.31, -Math.PI]} />
        <mesh name="MousePad" castShadow receiveShadow geometry={nodes.MousePad.geometry} material={materials.MousePad} position={[-1.75, 1.61, -0.37]} rotation={[0, 0.66, 0]} />
        <mesh name="Cube099" ref={Tesseract} castShadow receiveShadow geometry={nodes.Cube099.geometry} material={materials.spaceCube} position={[-2.14, 4.18, -1.4]} rotation={[-2.71, -0.09, -0.33]} > 
          <pointLight  position={[0,0,0]} intensity={2} distance={50} color={"#f00"} />
        </mesh>
        <mesh name="Cylinder002" castShadow receiveShadow geometry={nodes.Cylinder002.geometry} material={materials.Gears} position={[-2.14, 3.78, -1.41]} rotation={[0, Math.PI / 4, 0]} />
        <group name="Cube080" position={[-2.89, 4.07, -0.81]} rotation={[-1.57, 0, 2.36]}>
          <mesh name="Cube156" castShadow receiveShadow geometry={nodes.Cube156.geometry} material={materials.BookGreen} />
          <mesh name="Cube156_1" castShadow receiveShadow geometry={nodes.Cube156_1.geometry} material={materials.BookPage} />
        </group>
        <group name="Cube082" position={[-2.98, 4.07, -0.77]} rotation={[-1.57, 0, 2.36]}>
          <mesh name="Cube157" castShadow receiveShadow geometry={nodes.Cube157.geometry} material={materials.BookRed} />
          <mesh name="Cube157_1" castShadow receiveShadow geometry={nodes.Cube157_1.geometry} material={materials.BookPage} />
        </group>
        <group name="Cube086" position={[-3.02, 4.07, -0.7]} rotation={[-1.57, 0, 2.36]}>
          <mesh name="Cube158" castShadow receiveShadow geometry={nodes.Cube158.geometry} material={materials.BookBlue} />
          <mesh name="Cube158_1" castShadow receiveShadow geometry={nodes.Cube158_1.geometry} material={materials.BookPage} />
        </group>
        <group name="Cube087" position={[-3.12, 4.07, -0.66]} rotation={[-1.57, 0, 2.36]}>
          <mesh name="Cube159" castShadow receiveShadow geometry={nodes.Cube159.geometry} material={materials.BookRed} />
          <mesh name="Cube159_1" castShadow receiveShadow geometry={nodes.Cube159_1.geometry} material={materials.BookPage} />
        </group>
        <group name="Cube088" position={[-2.78, 4.07, -1]} rotation={[-1.25, -0.3, 2.41]}>
          <mesh name="Cube160" castShadow receiveShadow geometry={nodes.Cube160.geometry} material={materials['Rocket.001']} />
          <mesh name="Cube160_1" castShadow receiveShadow geometry={nodes.Cube160_1.geometry} material={materials.BookPage} />
        </group>
        <group name="Cube093" position={[-3.19, 3.82, -0.32]} rotation={[0, Math.PI / 4, 0]}>
          <mesh name="Cube161" castShadow receiveShadow geometry={nodes.Cube161.geometry} material={materials.BookBlue} />
          <mesh name="Cube161_1" castShadow receiveShadow geometry={nodes.Cube161_1.geometry} material={materials.BookPage} />
        </group>
        <group name="Cube094" position={[-3.57, 3.85, 0]} rotation={[-3, 0.61, 2.99]}>
          <mesh name="Cube162" castShadow receiveShadow geometry={nodes.Cube162.geometry} material={materials.BookGreen} />
          <mesh name="Cube162_1" castShadow receiveShadow geometry={nodes.Cube162_1.geometry} material={materials.BookPage} />
        </group>
        <group name="Cube065" position={[-2.91, 5.4, -0.53]} rotation={[-0.12, -0.28, -0.1]}>
          <mesh name="Cube154" castShadow receiveShadow geometry={nodes.Cube154.geometry} material={materials.BookGreen} />
          <mesh name="Cube154_1" castShadow receiveShadow geometry={nodes.Cube154_1.geometry} material={materials.BookPage} />
        </group>
        <group name="Cube076" position={[-3.16, 5.33, -0.25]} rotation={[0, Math.PI / 4, 0]}>
          <mesh name="Cube155" castShadow receiveShadow geometry={nodes.Cube155.geometry} material={materials.BookBlue} />
          <mesh name="Cube155_1" castShadow receiveShadow geometry={nodes.Cube155_1.geometry} material={materials.BookPage} />
        </group>
        <group name="Cube105" position={[1.87, 1.87, -1.83]} rotation={[0, Math.PI / 4, 0]} scale={[1, 0.69, 1]}>
          <mesh name="Cube_1" castShadow receiveShadow geometry={nodes.Cube_1.geometry} material={materials.AracadeBody} />
          <mesh name="Cube_2" castShadow receiveShadow geometry={nodes.Cube_2.geometry} material={materials['Rocket.001']} />
          <mesh name="Cube_3" castShadow receiveShadow geometry={nodes.Cube_3.geometry} material={materials.AracadeButton} />
        </group>
        <mesh name="arcadeScreen001" ref={ArcadeScreen} castShadow receiveShadow geometry={nodes.arcadeScreen001.geometry} material={materials['Screen.001']} position={[1.87, 1.87, -1.83]} rotation={[0, Math.PI / 4, 0]} scale={[1, 0.69, 1]} />
        <mesh name="Cylinder004" castShadow receiveShadow geometry={nodes.Cylinder004.geometry} material={materials['Material.001']} position={[6.03, 4.22, 1.16]} rotation={[0.03, 0.79, -1.59]} />
        <mesh name="Cylinder005" castShadow receiveShadow geometry={nodes.Cylinder005.geometry} material={materials['Material.001']} position={[5.76, 4.19, 1.39]} rotation={[1.55, 0.02, 0.79]} />
        <mesh name="Cylinder006" castShadow receiveShadow geometry={nodes.Cylinder006.geometry} material={materials['Material.001']} position={[6.07, 6.6, 1.2]} rotation={[0.03, 0.79, -1.59]} />
       <mesh name="Cylinder007" ref={bigGear} castShadow receiveShadow geometry={nodes.Cylinder007.geometry} material={materials['Material.001']} position={[5.05, 0.28, 2.46]} rotation={[-Math.PI, Math.PI / 4, Math.PI / 2]} />
        <mesh name="Cylinder003" castShadow receiveShadow geometry={nodes.Cylinder003.geometry} material={materials['Material.001']} position={[4.27, 4.74, -0.64]} rotation={[0, Math.PI / 4, -Math.PI / 2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/portfolio-room-arcade.glb')

export default RoomModel